- name: Build and Push Docker Images
  hosts: local
  vars_files:
    - group_vars/all.yml
  tasks:
    - name: Build backend image
      shell: docker build -t {{ reemaalsubaie24 }}/backend:latest ./backend

    - name: Build frontend image
      shell: docker build -t {{ reemaalsubaie24 }}/frontend:latest ./frontend

    - name: Login to Docker Hub
      shell: echo "{{ dockerhub_password }}" | docker login -u {{ reemaalsubaie24 }} --password-stdin

    - name: Push backend image
      shell: docker push {{ reemaalsubaie24 }}/backend:latest

    - name: Push frontend image
      shell: docker push {{ reemaalsubaie24 }}/frontend:latest
