---
- name: Build Docker Image
  hosts: localhost
  connection: local
  tasks:
    - name: Build Docker image
      community.docker.docker_image:
        name: "{{ backend_image }}"
        build:
          path: "{{ build_context }}"
        source: build
        state: present
        
    - name: Build Docker image
      community.docker.docker_image:
        name: "{{ frontend_image }}"
        build:
          path: "{{ build_context }}"
        source: build
        state: present
