---
- name: Build Docker Image
  hosts: localhost
  connection: local
  vars:
    workspace: "{{ lookup('env','WORKSPACE') | default(playbook_dir ~ '/..', true) }}"
  tasks:
    - name: Build Docker image
      community.docker.docker_image:
        name: "{{ backend_image }}"
        source: build
        build:
          path: "{{ workspace }}/backend"
        pull: yes
        
    - name: Build Docker image
      community.docker.docker_image:
        name: "{{ frontend_image }}"
        source: build
        build:
          path: "{{ workspace }}/forntend"
        pull: yes
