- name: Build Docker Images
  hosts: localhost
  connection: local

  tasks:
    - name: Build backend image
      command: docker build -t {{ backend_image }} -f backend/Dockerfile ./backend
      args:
        chdir: "{{ playbook_dir }}/.."

    - name: Build frontend image
      command: docker build -t {{ frontend_image }} -f frontend/Dockerfile ./frontend
      args:
        chdir: "{{ playbook_dir }}/.."
