---
- name: Deploy FullStack Project on Kubernetes
  hosts: k8s_server
  become: true

  vars:
    build_number: "{{ lookup('env','BUILD_NUMBER') | default('dev', true) }}"
    backend_image: "docker.io/reemaalsubaie24/backend-demo:{{ build_number }}"
    frontend_image: "docker.io/reemaalsubaie24/frontend:{{ build_number }}"
    kubeconfig_path: "/home/ubuntu/.kube/config"
    repo_root: "{{ playbook_dir | dirname }}"  
    ns: "fullstack"    

  tasks:

    # >>>>>>>>>>>>>>>>>   NAMESPACE   <<<<<<<<<<<<<<<<<<<<<
    - name: Copy Namespace Manifest File   # Copy namespace.yaml to server
      copy:
        src: "{{ repo_root }}/k8s/namespace.yaml"
        dest: /home/ubuntu/namespace.yaml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Apply Namespace to Cluster   # Apply namespace file to Kubernetes
      command: kubectl apply -f /home/ubuntu/namespace.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"


    # >>>>>>>>>>>>>>>>>>>   MYSQL   <<<<<<<<<<<<<<<<<<<<<<<
    - name: Copy MySQL PVC Manifest File   # Copy mysql-pvc.yaml to server
      copy:
        src: "{{ repo_root }}/k8s/mysql-pvc.yaml"
        dest: /home/ubuntu/mysql-pvc.yaml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Copy MySQL PV Manifest File   # Copy mysql-pv.yaml to server
      copy:
        src: "{{ repo_root }}/k8s/mysql-pv.yaml"
        dest: /home/ubuntu/mysql-pv.yaml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Copy MySQL Deployment Manifest File   # Copy mysql-deployment.yaml
      copy:
        src: "{{ repo_root }}/k8s/mysql-deployment.yaml"
        dest: /home/ubuntu/mysql-deployment.yaml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Apply MySQL PV   # Apply mysql-pv.yaml
      command: kubectl apply -f /home/ubuntu/mysql-pv.yaml 
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Apply MySQL PVC   # Apply mysql-pvc.yaml
      command: kubectl apply -f /home/ubuntu/mysql-pvc.yaml 
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Delete Old MySQL Deployment   # Remove old MySQL if exists
      command: kubectl -n {{ ns }} delete deployment mysql --ignore-not-found
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Apply MySQL Deployment   # Deploy MySQL
      command: kubectl apply -f /home/ubuntu/mysql-deployment.yaml -n {{ ns }}
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"


    # >>>>>>>>>>>>>>>>>>>   BACKEND   <<<<<<<<<<<<<<<<<<<<
    - name: Render Backend Deployment with Image Tag
      template:
        src: "{{ repo_root }}/k8s/Backend-Deployment.yaml"
        dest: /home/ubuntu/Backend-Deployment.yaml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Check Backend Deployment
      command: kubectl -n {{ ns }} get deployment backend-deployment
      register: be_check
      failed_when: false
      changed_when: false
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Delete Old Backend Deployment
      command: kubectl -n {{ ns }} delete deployment backend-deployment
      when: be_check.rc == 0
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Apply Backend Deployment
      command: kubectl apply -f /home/ubuntu/Backend-Deployment.yaml -n {{ ns }}
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"


    # >>>>>>>>>>>>>>>>>>>   FRONTEND   <<<<<<<<<<<<<<<<<<<
    - name: Render Frontend Deployment with Image Tag
      template:
        src: "{{ repo_root }}/k8s/Frontend-Deployment.yaml"
        dest: /home/ubuntu/Frontend-Deployment.yaml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Check Frontend Deployment
      command: kubectl -n {{ ns }} get deployment frontend-deployment
      register: fe_check
      failed_when: false
      changed_when: false
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Delete Old Frontend Deployment
      command: kubectl -n {{ ns }} delete deployment frontend-deployment
      when: fe_check.rc == 0
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Apply Frontend Deployment
      command: kubectl apply -f /home/ubuntu/Frontend-Deployment.yaml -n {{ ns }}
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"


    # >>>>>>>>>>>>>>>>>>>   INGRESS   <<<<<<<<<<<<<<<<<<<<<
    - name: Copy Frontend Ingress Manifest File
      copy:
        src: "{{ repo_root }}/k8s/ingress-frontend.yaml"
        dest: /home/ubuntu/ingress-frontend.yaml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Apply Frontend Ingress
      command: kubectl apply -f /home/ubuntu/ingress-frontend.yaml -n {{ ns }}
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Copy Backend Ingress Manifest File
      copy:
        src: "{{ repo_root }}/k8s/ingress-backend.yaml"
        dest: /home/ubuntu/ingress-backend.yaml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Apply Backend Ingress
      command: kubectl apply -f /home/ubuntu/ingress-backend.yaml -n {{ ns }}
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

