- name: Deploy app on Kubernetes
  hosts: k8s_server
  become: true

  vars:
    backend_image: "{{ backend_image }}"
    frontend_image: "{{ frontend_image }}"
    kubeconfig_path: "/home/ubuntu/.kube/config"
    repo_root: "{{ playbook_dir | dirname }}"

  tasks:
    # MySQL
    - name: Apply MySQL
      command: kubectl apply -f {{ repo_root }}/k8s/mysql-deployment.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    # Backend
    - name: Render backend deployment
      template:
        src: "{{ repo_root }}/k8s/backend-deployment.yaml.j2"
        dest: /home/ubuntu/backend-deployment.yaml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Delete old backend deployment if exists
      command: kubectl delete deployment demo-backend
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      failed_when: false

    - name: Apply backend deployment
      command: kubectl apply -f /home/ubuntu/backend-deployment.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    # Frontend
    - name: Render frontend deployment
      template:
        src: "{{ repo_root }}/k8s/frontend-deployment.yaml.j2"
        dest: /home/ubuntu/frontend-deployment.yaml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Delete old frontend deployment if exists
      command: kubectl delete deployment demo-frontend
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      failed_when: false

    - name: Apply frontend deployment
      command: kubectl apply -f /home/ubuntu/frontend-deployment.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
