- name: Deploy to Kubernetes
  hosts: k8s_server
  tasks:
    - name: Apply MySQL Deployment
      command: kubectl apply -f /home/ubuntu/FullStackProject/k8s/mysql-deployment.yaml

    - name: Apply Backend Deployment
      command: kubectl apply -f /home/ubuntu/FullStackProject/k8s/backend-deployment.yaml

    - name: Apply Frontend Deployment
      command: kubectl apply -f /home/ubuntu/FullStackProject/k8s/frontend-deployment.yaml
