    - name: Render backend deployment from template
      template:
        src: backend-deployment.yaml.j2
        dest: /home/ubuntu/backend-deployment.yaml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Apply Backend Deployment
      command: kubectl apply -f /home/ubuntu/backend-deployment.yaml

    - name: Render frontend deployment from template
      template:
        src: frontend-deployment.yaml.j2
        dest: /home/ubuntu/frontend-deployment.yaml
        owner: ubuntu
        group: ubuntu
        mode: '0644'
