---
- name: Deploy full-stack on Kubernetes
  hosts: k8s_server
  become: true

  vars:
    build_number: "{{ lookup('env','BUILD_NUMBER') | default('dev', true) }}"
    backend_image: "docker.io/reemaalsubaie24/backend:{{ build_number }}"
    frontend_image: "docker.io/reemaalsubaie24/frontend:{{ build_number }}"
    kubeconfig_path: "/home/ubuntu/.kube/config"
    repo_root: "{{ playbook_dir | dirname }}"
    backend_deploy_name: "backend-deployment"
    frontend_deploy_name: "frontend-deployment"

  tasks:
    # ===== MySQL (Apply دائمًا)
    - name: Apply MySQL manifest
      command: kubectl apply -f {{ repo_root }}/k8s/mysql-deployment.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    # ===== Backend + Frontend (Dynamic with loop)
    - name: Render manifests with injected images
      template:
        src: "{{ repo_root }}/k8s/{{ item.src }}"
        dest: "/home/ubuntu/{{ item.dest }}"
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      loop:
        - { src: "Backend-Deployment.yaml", dest: "backend-deployment.yaml" }
        - { src: "Frontend-Deployment.yaml", dest: "frontend-deployment.yaml" }

    - name: Apply manifests (backend + frontend)
      command: kubectl apply -f /home/ubuntu/{{ item }}
      loop:
        - backend-deployment.yaml
        - frontend-deployment.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Force rollout restart (backend & frontend)
      command: kubectl rollout restart deployment/{{ item }}
      loop:
        - "{{ backend_deploy_name }}"
        - "{{ frontend_deploy_name }}"
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
