---
- name: Push Docker Image
  hosts: localhost
  connection: local
  vars:
    backend_image: "reemaalsubaie24/backend-demo:{{ lookup('env','BUILD_NUMBER') }}"
    frontend_image: "reemaalsubaie24/frontend:{{ lookup('env','BUILD_NUMBER') }}"

  tasks:
    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
        password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"

    - name: Push backend Docker image
      community.docker.docker_image:
        name: "{{ backend_image }}"
        source: local
        push: yes
        state: present

    - name: Push frontend Docker image
      community.docker.docker_image:
        name: "{{ frontend_image }}"
        source: local
        push: yes
        state: present
