---
- name: Push Docker Images
  hosts: localhost
  connection: local

  vars:
    build_number: "{{ lookup('env','BUILD_NUMBER') | default('dev', true) }}"
    backend_image: "reemaalsubaie24/backend:{{ build_number }}"
    frontend_image: "reemaalsubaie24/frontend:{{ build_number }}"

  tasks:
    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
        password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"

    - name: Push backend Docker image
      community.docker.docker_image:
        name: "{{ backend_image }}"
        push: yes
        source: local

    - name: Push frontend Docker image
      community.docker.docker_image:
        name: "{{ frontend_image }}"
        push: yes
        source: local
